services:
  dgnet:
    build:
      context: .
      dockerfile: docker/dgnet/Dockerfile

    image: mesh-study-dgnet:cpu

    working_dir: /workspace/dgnet

    volumes:
      - ./models/dgnet:/workspace/dgnet
      - ./datasets:/workspace/datasets
      - ./configs/dgnet:/workspace/configs
      - ./results/dgnet:/workspace/results

    environment:
      PYTHONPATH: /workspace/dgnet

    stdin_open: true
    tty: true
